/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtegidoRouteImport } from './routes/_protegido'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'
import { Route as AppEntrarRouteImport } from './routes/app.entrar'
import { Route as AppInicioRouteImport } from './routes/app.inicio'
import { Route as AppNovoPinRouteImport } from './routes/app.novo-pin'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppQuizRouteImport } from './routes/app.quiz'
import { Route as AppRelatarRouteImport } from './routes/app.relatar'
import { Route as AppRelatosRouteImport } from './routes/app.relatos'
import { Route as AppTermoRouteImport } from './routes/app.termo'
import { Route as PainelLoginRouteImport } from './routes/painel.login'
import { Route as RespeitoCodigoRouteImport } from './routes/respeito.$codigo'
import { Route as ProtegidoPainelIndexRouteImport } from './routes/_protegido.painel.index'
import { Route as ProtegidoPainelEventosRouteImport } from './routes/_protegido.painel.eventos'
import { Route as ProtegidoPainelRankingRouteImport } from './routes/_protegido.painel.ranking'
import { Route as ProtegidoPainelRelatosRouteImport } from './routes/_protegido.painel.relatos'
import { Route as ProtegidoPainelRespeitoRouteImport } from './routes/_protegido.painel.respeito'
import { Route as ProtegidoTvIndexRouteImport } from './routes/_protegido.tv.index'
import { Route as ProtegidoTvJogoRouteImport } from './routes/_protegido.tv.jogo'
import { Route as AppLocalLocalIdRouteImport } from './routes/app.local.$localId'
import { Route as AppTrilhaIndexRouteImport } from './routes/app.trilha.index'
import { Route as AppTrilhaLicaoIdRouteImport } from './routes/app.trilha.$licaoId'
import { Route as ProtegidoPainelCampanhasIndexRouteImport } from './routes/_protegido.painel.campanhas.index'
import { Route as ProtegidoPainelCampanhasIdRouteImport } from './routes/_protegido.painel.campanhas.$id'
import { Route as ProtegidoPainelPerguntasIndexRouteImport } from './routes/_protegido.painel.perguntas.index'
import { Route as ProtegidoPainelPerguntasImportarRouteImport } from './routes/_protegido.painel.perguntas.importar'
import { Route as ProtegidoTvCheckinEventoIdRouteImport } from './routes/_protegido.tv.checkin.$eventoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidoRoute = ProtegidoRouteImport.update({
  id: '/_protegido',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/app/checkin',
  path: '/app/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEntrarRoute = AppEntrarRouteImport.update({
  id: '/app/entrar',
  path: '/app/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/app/inicio',
  path: '/app/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNovoPinRoute = AppNovoPinRouteImport.update({
  id: '/app/novo-pin',
  path: '/app/novo-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/app/perfil',
  path: '/app/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/app/quiz',
  path: '/app/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatarRoute = AppRelatarRouteImport.update({
  id: '/app/relatar',
  path: '/app/relatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatosRoute = AppRelatosRouteImport.update({
  id: '/app/relatos',
  path: '/app/relatos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTermoRoute = AppTermoRouteImport.update({
  id: '/app/termo',
  path: '/app/termo',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelLoginRoute = PainelLoginRouteImport.update({
  id: '/painel/login',
  path: '/painel/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RespeitoCodigoRoute = RespeitoCodigoRouteImport.update({
  id: '/respeito/$codigo',
  path: '/respeito/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidoPainelIndexRoute = ProtegidoPainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => ProtegidoRoute,
} as any)
const ProtegidoPainelEventosRoute = ProtegidoPainelEventosRouteImport.update({
  id: '/painel/eventos',
  path: '/painel/eventos',
  getParentRoute: () => ProtegidoRoute,
} as any)
const ProtegidoPainelRankingRoute = ProtegidoPainelRankingRouteImport.update({
  id: '/painel/ranking',
  path: '/painel/ranking',
  getParentRoute: () => ProtegidoRoute,
} as any)
const ProtegidoPainelRelatosRoute = ProtegidoPainelRelatosRouteImport.update({
  id: '/painel/relatos',
  path: '/painel/relatos',
  getParentRoute: () => ProtegidoRoute,
} as any)
const ProtegidoPainelRespeitoRoute = ProtegidoPainelRespeitoRouteImport.update({
  id: '/painel/respeito',
  path: '/painel/respeito',
  getParentRoute: () => ProtegidoRoute,
} as any)
const ProtegidoTvIndexRoute = ProtegidoTvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => ProtegidoRoute,
} as any)
const ProtegidoTvJogoRoute = ProtegidoTvJogoRouteImport.update({
  id: '/tv/jogo',
  path: '/tv/jogo',
  getParentRoute: () => ProtegidoRoute,
} as any)
const AppLocalLocalIdRoute = AppLocalLocalIdRouteImport.update({
  id: '/app/local/$localId',
  path: '/app/local/$localId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrilhaIndexRoute = AppTrilhaIndexRouteImport.update({
  id: '/app/trilha/',
  path: '/app/trilha/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrilhaLicaoIdRoute = AppTrilhaLicaoIdRouteImport.update({
  id: '/app/trilha/$licaoId',
  path: '/app/trilha/$licaoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidoPainelCampanhasIndexRoute =
  ProtegidoPainelCampanhasIndexRouteImport.update({
    id: '/painel/campanhas/',
    path: '/painel/campanhas/',
    getParentRoute: () => ProtegidoRoute,
  } as any)
const ProtegidoPainelCampanhasIdRoute =
  ProtegidoPainelCampanhasIdRouteImport.update({
    id: '/painel/campanhas/$id',
    path: '/painel/campanhas/$id',
    getParentRoute: () => ProtegidoRoute,
  } as any)
const ProtegidoPainelPerguntasIndexRoute =
  ProtegidoPainelPerguntasIndexRouteImport.update({
    id: '/painel/perguntas/',
    path: '/painel/perguntas/',
    getParentRoute: () => ProtegidoRoute,
  } as any)
const ProtegidoPainelPerguntasImportarRoute =
  ProtegidoPainelPerguntasImportarRouteImport.update({
    id: '/painel/perguntas/importar',
    path: '/painel/perguntas/importar',
    getParentRoute: () => ProtegidoRoute,
  } as any)
const ProtegidoTvCheckinEventoIdRoute =
  ProtegidoTvCheckinEventoIdRouteImport.update({
    id: '/tv/checkin/$eventoId',
    path: '/tv/checkin/$eventoId',
    getParentRoute: () => ProtegidoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/entrar': typeof AppEntrarRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/novo-pin': typeof AppNovoPinRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/relatar': typeof AppRelatarRoute
  '/app/relatos': typeof AppRelatosRoute
  '/app/termo': typeof AppTermoRoute
  '/painel/login': typeof PainelLoginRoute
  '/respeito/$codigo': typeof RespeitoCodigoRoute
  '/painel/eventos': typeof ProtegidoPainelEventosRoute
  '/painel/ranking': typeof ProtegidoPainelRankingRoute
  '/painel/relatos': typeof ProtegidoPainelRelatosRoute
  '/painel/respeito': typeof ProtegidoPainelRespeitoRoute
  '/tv/jogo': typeof ProtegidoTvJogoRoute
  '/app/local/$localId': typeof AppLocalLocalIdRoute
  '/app/trilha/$licaoId': typeof AppTrilhaLicaoIdRoute
  '/painel/': typeof ProtegidoPainelIndexRoute
  '/tv/': typeof ProtegidoTvIndexRoute
  '/app/trilha/': typeof AppTrilhaIndexRoute
  '/painel/campanhas/$id': typeof ProtegidoPainelCampanhasIdRoute
  '/painel/perguntas/importar': typeof ProtegidoPainelPerguntasImportarRoute
  '/tv/checkin/$eventoId': typeof ProtegidoTvCheckinEventoIdRoute
  '/painel/campanhas/': typeof ProtegidoPainelCampanhasIndexRoute
  '/painel/perguntas/': typeof ProtegidoPainelPerguntasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/entrar': typeof AppEntrarRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/novo-pin': typeof AppNovoPinRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/relatar': typeof AppRelatarRoute
  '/app/relatos': typeof AppRelatosRoute
  '/app/termo': typeof AppTermoRoute
  '/painel/login': typeof PainelLoginRoute
  '/respeito/$codigo': typeof RespeitoCodigoRoute
  '/painel/eventos': typeof ProtegidoPainelEventosRoute
  '/painel/ranking': typeof ProtegidoPainelRankingRoute
  '/painel/relatos': typeof ProtegidoPainelRelatosRoute
  '/painel/respeito': typeof ProtegidoPainelRespeitoRoute
  '/tv/jogo': typeof ProtegidoTvJogoRoute
  '/app/local/$localId': typeof AppLocalLocalIdRoute
  '/app/trilha/$licaoId': typeof AppTrilhaLicaoIdRoute
  '/painel': typeof ProtegidoPainelIndexRoute
  '/tv': typeof ProtegidoTvIndexRoute
  '/app/trilha': typeof AppTrilhaIndexRoute
  '/painel/campanhas/$id': typeof ProtegidoPainelCampanhasIdRoute
  '/painel/perguntas/importar': typeof ProtegidoPainelPerguntasImportarRoute
  '/tv/checkin/$eventoId': typeof ProtegidoTvCheckinEventoIdRoute
  '/painel/campanhas': typeof ProtegidoPainelCampanhasIndexRoute
  '/painel/perguntas': typeof ProtegidoPainelPerguntasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protegido': typeof ProtegidoRouteWithChildren
  '/app/checkin': typeof AppCheckinRoute
  '/app/entrar': typeof AppEntrarRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/novo-pin': typeof AppNovoPinRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/relatar': typeof AppRelatarRoute
  '/app/relatos': typeof AppRelatosRoute
  '/app/termo': typeof AppTermoRoute
  '/painel/login': typeof PainelLoginRoute
  '/respeito/$codigo': typeof RespeitoCodigoRoute
  '/_protegido/painel/eventos': typeof ProtegidoPainelEventosRoute
  '/_protegido/painel/ranking': typeof ProtegidoPainelRankingRoute
  '/_protegido/painel/relatos': typeof ProtegidoPainelRelatosRoute
  '/_protegido/painel/respeito': typeof ProtegidoPainelRespeitoRoute
  '/_protegido/tv/jogo': typeof ProtegidoTvJogoRoute
  '/app/local/$localId': typeof AppLocalLocalIdRoute
  '/app/trilha/$licaoId': typeof AppTrilhaLicaoIdRoute
  '/_protegido/painel/': typeof ProtegidoPainelIndexRoute
  '/_protegido/tv/': typeof ProtegidoTvIndexRoute
  '/app/trilha/': typeof AppTrilhaIndexRoute
  '/_protegido/painel/campanhas/$id': typeof ProtegidoPainelCampanhasIdRoute
  '/_protegido/painel/perguntas/importar': typeof ProtegidoPainelPerguntasImportarRoute
  '/_protegido/tv/checkin/$eventoId': typeof ProtegidoTvCheckinEventoIdRoute
  '/_protegido/painel/campanhas/': typeof ProtegidoPainelCampanhasIndexRoute
  '/_protegido/painel/perguntas/': typeof ProtegidoPainelPerguntasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/checkin'
    | '/app/entrar'
    | '/app/inicio'
    | '/app/novo-pin'
    | '/app/perfil'
    | '/app/quiz'
    | '/app/relatar'
    | '/app/relatos'
    | '/app/termo'
    | '/painel/login'
    | '/respeito/$codigo'
    | '/painel/eventos'
    | '/painel/ranking'
    | '/painel/relatos'
    | '/painel/respeito'
    | '/tv/jogo'
    | '/app/local/$localId'
    | '/app/trilha/$licaoId'
    | '/painel/'
    | '/tv/'
    | '/app/trilha/'
    | '/painel/campanhas/$id'
    | '/painel/perguntas/importar'
    | '/tv/checkin/$eventoId'
    | '/painel/campanhas/'
    | '/painel/perguntas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/checkin'
    | '/app/entrar'
    | '/app/inicio'
    | '/app/novo-pin'
    | '/app/perfil'
    | '/app/quiz'
    | '/app/relatar'
    | '/app/relatos'
    | '/app/termo'
    | '/painel/login'
    | '/respeito/$codigo'
    | '/painel/eventos'
    | '/painel/ranking'
    | '/painel/relatos'
    | '/painel/respeito'
    | '/tv/jogo'
    | '/app/local/$localId'
    | '/app/trilha/$licaoId'
    | '/painel'
    | '/tv'
    | '/app/trilha'
    | '/painel/campanhas/$id'
    | '/painel/perguntas/importar'
    | '/tv/checkin/$eventoId'
    | '/painel/campanhas'
    | '/painel/perguntas'
  id:
    | '__root__'
    | '/'
    | '/_protegido'
    | '/app/checkin'
    | '/app/entrar'
    | '/app/inicio'
    | '/app/novo-pin'
    | '/app/perfil'
    | '/app/quiz'
    | '/app/relatar'
    | '/app/relatos'
    | '/app/termo'
    | '/painel/login'
    | '/respeito/$codigo'
    | '/_protegido/painel/eventos'
    | '/_protegido/painel/ranking'
    | '/_protegido/painel/relatos'
    | '/_protegido/painel/respeito'
    | '/_protegido/tv/jogo'
    | '/app/local/$localId'
    | '/app/trilha/$licaoId'
    | '/_protegido/painel/'
    | '/_protegido/tv/'
    | '/app/trilha/'
    | '/_protegido/painel/campanhas/$id'
    | '/_protegido/painel/perguntas/importar'
    | '/_protegido/tv/checkin/$eventoId'
    | '/_protegido/painel/campanhas/'
    | '/_protegido/painel/perguntas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtegidoRoute: typeof ProtegidoRouteWithChildren
  AppCheckinRoute: typeof AppCheckinRoute
  AppEntrarRoute: typeof AppEntrarRoute
  AppInicioRoute: typeof AppInicioRoute
  AppNovoPinRoute: typeof AppNovoPinRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppQuizRoute: typeof AppQuizRoute
  AppRelatarRoute: typeof AppRelatarRoute
  AppRelatosRoute: typeof AppRelatosRoute
  AppTermoRoute: typeof AppTermoRoute
  PainelLoginRoute: typeof PainelLoginRoute
  RespeitoCodigoRoute: typeof RespeitoCodigoRoute
  AppLocalLocalIdRoute: typeof AppLocalLocalIdRoute
  AppTrilhaLicaoIdRoute: typeof AppTrilhaLicaoIdRoute
  AppTrilhaIndexRoute: typeof AppTrilhaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegido': {
      id: '/_protegido'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtegidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/app/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/entrar': {
      id: '/app/entrar'
      path: '/app/entrar'
      fullPath: '/app/entrar'
      preLoaderRoute: typeof AppEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inicio': {
      id: '/app/inicio'
      path: '/app/inicio'
      fullPath: '/app/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/novo-pin': {
      id: '/app/novo-pin'
      path: '/app/novo-pin'
      fullPath: '/app/novo-pin'
      preLoaderRoute: typeof AppNovoPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/app/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/app/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/relatar': {
      id: '/app/relatar'
      path: '/app/relatar'
      fullPath: '/app/relatar'
      preLoaderRoute: typeof AppRelatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/relatos': {
      id: '/app/relatos'
      path: '/app/relatos'
      fullPath: '/app/relatos'
      preLoaderRoute: typeof AppRelatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/termo': {
      id: '/app/termo'
      path: '/app/termo'
      fullPath: '/app/termo'
      preLoaderRoute: typeof AppTermoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/login': {
      id: '/painel/login'
      path: '/painel/login'
      fullPath: '/painel/login'
      preLoaderRoute: typeof PainelLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respeito/$codigo': {
      id: '/respeito/$codigo'
      path: '/respeito/$codigo'
      fullPath: '/respeito/$codigo'
      preLoaderRoute: typeof RespeitoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegido/painel/': {
      id: '/_protegido/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof ProtegidoPainelIndexRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/eventos': {
      id: '/_protegido/painel/eventos'
      path: '/painel/eventos'
      fullPath: '/painel/eventos'
      preLoaderRoute: typeof ProtegidoPainelEventosRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/ranking': {
      id: '/_protegido/painel/ranking'
      path: '/painel/ranking'
      fullPath: '/painel/ranking'
      preLoaderRoute: typeof ProtegidoPainelRankingRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/relatos': {
      id: '/_protegido/painel/relatos'
      path: '/painel/relatos'
      fullPath: '/painel/relatos'
      preLoaderRoute: typeof ProtegidoPainelRelatosRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/respeito': {
      id: '/_protegido/painel/respeito'
      path: '/painel/respeito'
      fullPath: '/painel/respeito'
      preLoaderRoute: typeof ProtegidoPainelRespeitoRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/tv/': {
      id: '/_protegido/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof ProtegidoTvIndexRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/tv/jogo': {
      id: '/_protegido/tv/jogo'
      path: '/tv/jogo'
      fullPath: '/tv/jogo'
      preLoaderRoute: typeof ProtegidoTvJogoRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/app/local/$localId': {
      id: '/app/local/$localId'
      path: '/app/local/$localId'
      fullPath: '/app/local/$localId'
      preLoaderRoute: typeof AppLocalLocalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/trilha/': {
      id: '/app/trilha/'
      path: '/app/trilha'
      fullPath: '/app/trilha/'
      preLoaderRoute: typeof AppTrilhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/trilha/$licaoId': {
      id: '/app/trilha/$licaoId'
      path: '/app/trilha/$licaoId'
      fullPath: '/app/trilha/$licaoId'
      preLoaderRoute: typeof AppTrilhaLicaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegido/painel/campanhas/': {
      id: '/_protegido/painel/campanhas/'
      path: '/painel/campanhas'
      fullPath: '/painel/campanhas/'
      preLoaderRoute: typeof ProtegidoPainelCampanhasIndexRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/campanhas/$id': {
      id: '/_protegido/painel/campanhas/$id'
      path: '/painel/campanhas/$id'
      fullPath: '/painel/campanhas/$id'
      preLoaderRoute: typeof ProtegidoPainelCampanhasIdRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/perguntas/': {
      id: '/_protegido/painel/perguntas/'
      path: '/painel/perguntas'
      fullPath: '/painel/perguntas/'
      preLoaderRoute: typeof ProtegidoPainelPerguntasIndexRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/perguntas/importar': {
      id: '/_protegido/painel/perguntas/importar'
      path: '/painel/perguntas/importar'
      fullPath: '/painel/perguntas/importar'
      preLoaderRoute: typeof ProtegidoPainelPerguntasImportarRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/tv/checkin/$eventoId': {
      id: '/_protegido/tv/checkin/$eventoId'
      path: '/tv/checkin/$eventoId'
      fullPath: '/tv/checkin/$eventoId'
      preLoaderRoute: typeof ProtegidoTvCheckinEventoIdRouteImport
      parentRoute: typeof ProtegidoRoute
    }
  }
}

interface ProtegidoRouteChildren {
  ProtegidoPainelEventosRoute: typeof ProtegidoPainelEventosRoute
  ProtegidoPainelRankingRoute: typeof ProtegidoPainelRankingRoute
  ProtegidoPainelRelatosRoute: typeof ProtegidoPainelRelatosRoute
  ProtegidoPainelRespeitoRoute: typeof ProtegidoPainelRespeitoRoute
  ProtegidoTvJogoRoute: typeof ProtegidoTvJogoRoute
  ProtegidoPainelIndexRoute: typeof ProtegidoPainelIndexRoute
  ProtegidoTvIndexRoute: typeof ProtegidoTvIndexRoute
  ProtegidoPainelCampanhasIdRoute: typeof ProtegidoPainelCampanhasIdRoute
  ProtegidoPainelPerguntasImportarRoute: typeof ProtegidoPainelPerguntasImportarRoute
  ProtegidoTvCheckinEventoIdRoute: typeof ProtegidoTvCheckinEventoIdRoute
  ProtegidoPainelCampanhasIndexRoute: typeof ProtegidoPainelCampanhasIndexRoute
  ProtegidoPainelPerguntasIndexRoute: typeof ProtegidoPainelPerguntasIndexRoute
}

const ProtegidoRouteChildren: ProtegidoRouteChildren = {
  ProtegidoPainelEventosRoute: ProtegidoPainelEventosRoute,
  ProtegidoPainelRankingRoute: ProtegidoPainelRankingRoute,
  ProtegidoPainelRelatosRoute: ProtegidoPainelRelatosRoute,
  ProtegidoPainelRespeitoRoute: ProtegidoPainelRespeitoRoute,
  ProtegidoTvJogoRoute: ProtegidoTvJogoRoute,
  ProtegidoPainelIndexRoute: ProtegidoPainelIndexRoute,
  ProtegidoTvIndexRoute: ProtegidoTvIndexRoute,
  ProtegidoPainelCampanhasIdRoute: ProtegidoPainelCampanhasIdRoute,
  ProtegidoPainelPerguntasImportarRoute: ProtegidoPainelPerguntasImportarRoute,
  ProtegidoTvCheckinEventoIdRoute: ProtegidoTvCheckinEventoIdRoute,
  ProtegidoPainelCampanhasIndexRoute: ProtegidoPainelCampanhasIndexRoute,
  ProtegidoPainelPerguntasIndexRoute: ProtegidoPainelPerguntasIndexRoute,
}

const ProtegidoRouteWithChildren = ProtegidoRoute._addFileChildren(
  ProtegidoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtegidoRoute: ProtegidoRouteWithChildren,
  AppCheckinRoute: AppCheckinRoute,
  AppEntrarRoute: AppEntrarRoute,
  AppInicioRoute: AppInicioRoute,
  AppNovoPinRoute: AppNovoPinRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppQuizRoute: AppQuizRoute,
  AppRelatarRoute: AppRelatarRoute,
  AppRelatosRoute: AppRelatosRoute,
  AppTermoRoute: AppTermoRoute,
  PainelLoginRoute: PainelLoginRoute,
  RespeitoCodigoRoute: RespeitoCodigoRoute,
  AppLocalLocalIdRoute: AppLocalLocalIdRoute,
  AppTrilhaLicaoIdRoute: AppTrilhaLicaoIdRoute,
  AppTrilhaIndexRoute: AppTrilhaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
