/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtegidoRouteImport } from './routes/_protegido'
import { Route as AppEntrarRouteImport } from './routes/app.entrar'
import { Route as AppInicioRouteImport } from './routes/app.inicio'
import { Route as AppNovoPinRouteImport } from './routes/app.novo-pin'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppQuizRouteImport } from './routes/app.quiz'
import { Route as AppTermoRouteImport } from './routes/app.termo'
import { Route as PainelLoginRouteImport } from './routes/painel.login'
import { Route as ProtegidoPainelIndexRouteImport } from './routes/_protegido.painel.index'
import { Route as ProtegidoPainelEventosRouteImport } from './routes/_protegido.painel.eventos'
import { Route as AppTrilhaIndexRouteImport } from './routes/app.trilha.index'
import { Route as AppTrilhaLicaoIdRouteImport } from './routes/app.trilha.$licaoId'
import { Route as ProtegidoPainelCampanhasIndexRouteImport } from './routes/_protegido.painel.campanhas.index'
import { Route as ProtegidoPainelCampanhasIdRouteImport } from './routes/_protegido.painel.campanhas.$id'
import { Route as ProtegidoPainelPerguntasIndexRouteImport } from './routes/_protegido.painel.perguntas.index'
import { Route as ProtegidoPainelPerguntasImportarRouteImport } from './routes/_protegido.painel.perguntas.importar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidoRoute = ProtegidoRouteImport.update({
  id: '/_protegido',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEntrarRoute = AppEntrarRouteImport.update({
  id: '/app/entrar',
  path: '/app/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/app/inicio',
  path: '/app/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNovoPinRoute = AppNovoPinRouteImport.update({
  id: '/app/novo-pin',
  path: '/app/novo-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/app/perfil',
  path: '/app/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/app/quiz',
  path: '/app/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTermoRoute = AppTermoRouteImport.update({
  id: '/app/termo',
  path: '/app/termo',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelLoginRoute = PainelLoginRouteImport.update({
  id: '/painel/login',
  path: '/painel/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidoPainelIndexRoute = ProtegidoPainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => ProtegidoRoute,
} as any)
const ProtegidoPainelEventosRoute = ProtegidoPainelEventosRouteImport.update({
  id: '/painel/eventos',
  path: '/painel/eventos',
  getParentRoute: () => ProtegidoRoute,
} as any)
const AppTrilhaIndexRoute = AppTrilhaIndexRouteImport.update({
  id: '/app/trilha/',
  path: '/app/trilha/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrilhaLicaoIdRoute = AppTrilhaLicaoIdRouteImport.update({
  id: '/app/trilha/$licaoId',
  path: '/app/trilha/$licaoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidoPainelCampanhasIndexRoute =
  ProtegidoPainelCampanhasIndexRouteImport.update({
    id: '/painel/campanhas/',
    path: '/painel/campanhas/',
    getParentRoute: () => ProtegidoRoute,
  } as any)
const ProtegidoPainelCampanhasIdRoute =
  ProtegidoPainelCampanhasIdRouteImport.update({
    id: '/painel/campanhas/$id',
    path: '/painel/campanhas/$id',
    getParentRoute: () => ProtegidoRoute,
  } as any)
const ProtegidoPainelPerguntasIndexRoute =
  ProtegidoPainelPerguntasIndexRouteImport.update({
    id: '/painel/perguntas/',
    path: '/painel/perguntas/',
    getParentRoute: () => ProtegidoRoute,
  } as any)
const ProtegidoPainelPerguntasImportarRoute =
  ProtegidoPainelPerguntasImportarRouteImport.update({
    id: '/painel/perguntas/importar',
    path: '/painel/perguntas/importar',
    getParentRoute: () => ProtegidoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/entrar': typeof AppEntrarRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/novo-pin': typeof AppNovoPinRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/termo': typeof AppTermoRoute
  '/painel/login': typeof PainelLoginRoute
  '/painel/eventos': typeof ProtegidoPainelEventosRoute
  '/app/trilha/$licaoId': typeof AppTrilhaLicaoIdRoute
  '/painel/': typeof ProtegidoPainelIndexRoute
  '/app/trilha/': typeof AppTrilhaIndexRoute
  '/painel/campanhas/$id': typeof ProtegidoPainelCampanhasIdRoute
  '/painel/perguntas/importar': typeof ProtegidoPainelPerguntasImportarRoute
  '/painel/campanhas/': typeof ProtegidoPainelCampanhasIndexRoute
  '/painel/perguntas/': typeof ProtegidoPainelPerguntasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/entrar': typeof AppEntrarRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/novo-pin': typeof AppNovoPinRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/termo': typeof AppTermoRoute
  '/painel/login': typeof PainelLoginRoute
  '/painel/eventos': typeof ProtegidoPainelEventosRoute
  '/app/trilha/$licaoId': typeof AppTrilhaLicaoIdRoute
  '/painel': typeof ProtegidoPainelIndexRoute
  '/app/trilha': typeof AppTrilhaIndexRoute
  '/painel/campanhas/$id': typeof ProtegidoPainelCampanhasIdRoute
  '/painel/perguntas/importar': typeof ProtegidoPainelPerguntasImportarRoute
  '/painel/campanhas': typeof ProtegidoPainelCampanhasIndexRoute
  '/painel/perguntas': typeof ProtegidoPainelPerguntasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protegido': typeof ProtegidoRouteWithChildren
  '/app/entrar': typeof AppEntrarRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/novo-pin': typeof AppNovoPinRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/termo': typeof AppTermoRoute
  '/painel/login': typeof PainelLoginRoute
  '/_protegido/painel/eventos': typeof ProtegidoPainelEventosRoute
  '/app/trilha/$licaoId': typeof AppTrilhaLicaoIdRoute
  '/_protegido/painel/': typeof ProtegidoPainelIndexRoute
  '/app/trilha/': typeof AppTrilhaIndexRoute
  '/_protegido/painel/campanhas/$id': typeof ProtegidoPainelCampanhasIdRoute
  '/_protegido/painel/perguntas/importar': typeof ProtegidoPainelPerguntasImportarRoute
  '/_protegido/painel/campanhas/': typeof ProtegidoPainelCampanhasIndexRoute
  '/_protegido/painel/perguntas/': typeof ProtegidoPainelPerguntasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/entrar'
    | '/app/inicio'
    | '/app/novo-pin'
    | '/app/perfil'
    | '/app/quiz'
    | '/app/termo'
    | '/painel/login'
    | '/painel/eventos'
    | '/app/trilha/$licaoId'
    | '/painel/'
    | '/app/trilha/'
    | '/painel/campanhas/$id'
    | '/painel/perguntas/importar'
    | '/painel/campanhas/'
    | '/painel/perguntas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/entrar'
    | '/app/inicio'
    | '/app/novo-pin'
    | '/app/perfil'
    | '/app/quiz'
    | '/app/termo'
    | '/painel/login'
    | '/painel/eventos'
    | '/app/trilha/$licaoId'
    | '/painel'
    | '/app/trilha'
    | '/painel/campanhas/$id'
    | '/painel/perguntas/importar'
    | '/painel/campanhas'
    | '/painel/perguntas'
  id:
    | '__root__'
    | '/'
    | '/_protegido'
    | '/app/entrar'
    | '/app/inicio'
    | '/app/novo-pin'
    | '/app/perfil'
    | '/app/quiz'
    | '/app/termo'
    | '/painel/login'
    | '/_protegido/painel/eventos'
    | '/app/trilha/$licaoId'
    | '/_protegido/painel/'
    | '/app/trilha/'
    | '/_protegido/painel/campanhas/$id'
    | '/_protegido/painel/perguntas/importar'
    | '/_protegido/painel/campanhas/'
    | '/_protegido/painel/perguntas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtegidoRoute: typeof ProtegidoRouteWithChildren
  AppEntrarRoute: typeof AppEntrarRoute
  AppInicioRoute: typeof AppInicioRoute
  AppNovoPinRoute: typeof AppNovoPinRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppQuizRoute: typeof AppQuizRoute
  AppTermoRoute: typeof AppTermoRoute
  PainelLoginRoute: typeof PainelLoginRoute
  AppTrilhaLicaoIdRoute: typeof AppTrilhaLicaoIdRoute
  AppTrilhaIndexRoute: typeof AppTrilhaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegido': {
      id: '/_protegido'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtegidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/entrar': {
      id: '/app/entrar'
      path: '/app/entrar'
      fullPath: '/app/entrar'
      preLoaderRoute: typeof AppEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inicio': {
      id: '/app/inicio'
      path: '/app/inicio'
      fullPath: '/app/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/novo-pin': {
      id: '/app/novo-pin'
      path: '/app/novo-pin'
      fullPath: '/app/novo-pin'
      preLoaderRoute: typeof AppNovoPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/app/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/app/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/termo': {
      id: '/app/termo'
      path: '/app/termo'
      fullPath: '/app/termo'
      preLoaderRoute: typeof AppTermoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/login': {
      id: '/painel/login'
      path: '/painel/login'
      fullPath: '/painel/login'
      preLoaderRoute: typeof PainelLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegido/painel/': {
      id: '/_protegido/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof ProtegidoPainelIndexRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/eventos': {
      id: '/_protegido/painel/eventos'
      path: '/painel/eventos'
      fullPath: '/painel/eventos'
      preLoaderRoute: typeof ProtegidoPainelEventosRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/app/trilha/': {
      id: '/app/trilha/'
      path: '/app/trilha'
      fullPath: '/app/trilha/'
      preLoaderRoute: typeof AppTrilhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/trilha/$licaoId': {
      id: '/app/trilha/$licaoId'
      path: '/app/trilha/$licaoId'
      fullPath: '/app/trilha/$licaoId'
      preLoaderRoute: typeof AppTrilhaLicaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegido/painel/campanhas/': {
      id: '/_protegido/painel/campanhas/'
      path: '/painel/campanhas'
      fullPath: '/painel/campanhas/'
      preLoaderRoute: typeof ProtegidoPainelCampanhasIndexRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/campanhas/$id': {
      id: '/_protegido/painel/campanhas/$id'
      path: '/painel/campanhas/$id'
      fullPath: '/painel/campanhas/$id'
      preLoaderRoute: typeof ProtegidoPainelCampanhasIdRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/perguntas/': {
      id: '/_protegido/painel/perguntas/'
      path: '/painel/perguntas'
      fullPath: '/painel/perguntas/'
      preLoaderRoute: typeof ProtegidoPainelPerguntasIndexRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/painel/perguntas/importar': {
      id: '/_protegido/painel/perguntas/importar'
      path: '/painel/perguntas/importar'
      fullPath: '/painel/perguntas/importar'
      preLoaderRoute: typeof ProtegidoPainelPerguntasImportarRouteImport
      parentRoute: typeof ProtegidoRoute
    }
  }
}

interface ProtegidoRouteChildren {
  ProtegidoPainelEventosRoute: typeof ProtegidoPainelEventosRoute
  ProtegidoPainelIndexRoute: typeof ProtegidoPainelIndexRoute
  ProtegidoPainelCampanhasIdRoute: typeof ProtegidoPainelCampanhasIdRoute
  ProtegidoPainelPerguntasImportarRoute: typeof ProtegidoPainelPerguntasImportarRoute
  ProtegidoPainelCampanhasIndexRoute: typeof ProtegidoPainelCampanhasIndexRoute
  ProtegidoPainelPerguntasIndexRoute: typeof ProtegidoPainelPerguntasIndexRoute
}

const ProtegidoRouteChildren: ProtegidoRouteChildren = {
  ProtegidoPainelEventosRoute: ProtegidoPainelEventosRoute,
  ProtegidoPainelIndexRoute: ProtegidoPainelIndexRoute,
  ProtegidoPainelCampanhasIdRoute: ProtegidoPainelCampanhasIdRoute,
  ProtegidoPainelPerguntasImportarRoute: ProtegidoPainelPerguntasImportarRoute,
  ProtegidoPainelCampanhasIndexRoute: ProtegidoPainelCampanhasIndexRoute,
  ProtegidoPainelPerguntasIndexRoute: ProtegidoPainelPerguntasIndexRoute,
}

const ProtegidoRouteWithChildren = ProtegidoRoute._addFileChildren(
  ProtegidoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtegidoRoute: ProtegidoRouteWithChildren,
  AppEntrarRoute: AppEntrarRoute,
  AppInicioRoute: AppInicioRoute,
  AppNovoPinRoute: AppNovoPinRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppQuizRoute: AppQuizRoute,
  AppTermoRoute: AppTermoRoute,
  PainelLoginRoute: PainelLoginRoute,
  AppTrilhaLicaoIdRoute: AppTrilhaLicaoIdRoute,
  AppTrilhaIndexRoute: AppTrilhaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
