/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtegidoRouteImport } from './routes/_protegido'
import { Route as AppEntrarRouteImport } from './routes/app.entrar'
import { Route as AppInicioRouteImport } from './routes/app.inicio'
import { Route as AppNovoPinRouteImport } from './routes/app.novo-pin'
import { Route as AppQuizRouteImport } from './routes/app.quiz'
import { Route as AppTermoRouteImport } from './routes/app.termo'
import { Route as PainelLoginRouteImport } from './routes/painel.login'
import { Route as ProtegidoPainelIndexRouteImport } from './routes/_protegido.painel.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidoRoute = ProtegidoRouteImport.update({
  id: '/_protegido',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEntrarRoute = AppEntrarRouteImport.update({
  id: '/app/entrar',
  path: '/app/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/app/inicio',
  path: '/app/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNovoPinRoute = AppNovoPinRouteImport.update({
  id: '/app/novo-pin',
  path: '/app/novo-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/app/quiz',
  path: '/app/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTermoRoute = AppTermoRouteImport.update({
  id: '/app/termo',
  path: '/app/termo',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelLoginRoute = PainelLoginRouteImport.update({
  id: '/painel/login',
  path: '/painel/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidoPainelIndexRoute = ProtegidoPainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => ProtegidoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/entrar': typeof AppEntrarRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/novo-pin': typeof AppNovoPinRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/termo': typeof AppTermoRoute
  '/painel/login': typeof PainelLoginRoute
  '/painel/': typeof ProtegidoPainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/entrar': typeof AppEntrarRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/novo-pin': typeof AppNovoPinRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/termo': typeof AppTermoRoute
  '/painel/login': typeof PainelLoginRoute
  '/painel': typeof ProtegidoPainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protegido': typeof ProtegidoRouteWithChildren
  '/app/entrar': typeof AppEntrarRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/novo-pin': typeof AppNovoPinRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/termo': typeof AppTermoRoute
  '/painel/login': typeof PainelLoginRoute
  '/_protegido/painel/': typeof ProtegidoPainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/entrar'
    | '/app/inicio'
    | '/app/novo-pin'
    | '/app/quiz'
    | '/app/termo'
    | '/painel/login'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/entrar'
    | '/app/inicio'
    | '/app/novo-pin'
    | '/app/quiz'
    | '/app/termo'
    | '/painel/login'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_protegido'
    | '/app/entrar'
    | '/app/inicio'
    | '/app/novo-pin'
    | '/app/quiz'
    | '/app/termo'
    | '/painel/login'
    | '/_protegido/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtegidoRoute: typeof ProtegidoRouteWithChildren
  AppEntrarRoute: typeof AppEntrarRoute
  AppInicioRoute: typeof AppInicioRoute
  AppNovoPinRoute: typeof AppNovoPinRoute
  AppQuizRoute: typeof AppQuizRoute
  AppTermoRoute: typeof AppTermoRoute
  PainelLoginRoute: typeof PainelLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegido': {
      id: '/_protegido'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtegidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/entrar': {
      id: '/app/entrar'
      path: '/app/entrar'
      fullPath: '/app/entrar'
      preLoaderRoute: typeof AppEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inicio': {
      id: '/app/inicio'
      path: '/app/inicio'
      fullPath: '/app/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/novo-pin': {
      id: '/app/novo-pin'
      path: '/app/novo-pin'
      fullPath: '/app/novo-pin'
      preLoaderRoute: typeof AppNovoPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/app/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/termo': {
      id: '/app/termo'
      path: '/app/termo'
      fullPath: '/app/termo'
      preLoaderRoute: typeof AppTermoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/login': {
      id: '/painel/login'
      path: '/painel/login'
      fullPath: '/painel/login'
      preLoaderRoute: typeof PainelLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegido/painel/': {
      id: '/_protegido/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof ProtegidoPainelIndexRouteImport
      parentRoute: typeof ProtegidoRoute
    }
  }
}

interface ProtegidoRouteChildren {
  ProtegidoPainelIndexRoute: typeof ProtegidoPainelIndexRoute
}

const ProtegidoRouteChildren: ProtegidoRouteChildren = {
  ProtegidoPainelIndexRoute: ProtegidoPainelIndexRoute,
}

const ProtegidoRouteWithChildren = ProtegidoRoute._addFileChildren(
  ProtegidoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtegidoRoute: ProtegidoRouteWithChildren,
  AppEntrarRoute: AppEntrarRoute,
  AppInicioRoute: AppInicioRoute,
  AppNovoPinRoute: AppNovoPinRoute,
  AppQuizRoute: AppQuizRoute,
  AppTermoRoute: AppTermoRoute,
  PainelLoginRoute: PainelLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
